services:
  mongo-front:
    container_name: mongo-front
    build:
      context: ../mongo-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mongo-front-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/index.html || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    depends_on:
      mongo-back:
        condition: service_healthy

  mongo-back:
    container_name: mongo-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MODE=dev
      - MONGODB_HOST=mongo-db
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    networks:
      - mongo-back-network
      - mongo-front-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
    depends_on:
      mongo-db:
        condition: service_healthy
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongo-db-vol:/data/db
    networks:
      - mongo-back-network
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s

volumes:
  mongo-db-vol:
networks:
  mongo-front-network:
  mongo-back-network:
